name: Docker Image CI

on:
  push:
#     branches: [ main ]
    tags: 'ci-test'
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changed files
      run: echo "::set-output name=CHANGED_FILES::$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})"
      id: changed_files

    - run: echo "the changed files are ${{steps.changed_files.outputs.CHANGED_FILES}}"

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - run: echo "the current version is ${{steps.get_version.outputs.VERSION}}"
  
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{steps.changed_files.outputs.CHANGED_FILES}}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab-base:ci-test

# jobs:
#   build:
#     name: Build the Docker image
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
      
#     - name: Get file changes
#       id: get_file_changes
#       uses: dorner/file-changes-action@v1.2.0
#       with:
#         githubToken: ${{ secrets.GITHUB_TOKEN }}
#         plaintext: true

#     - name: Echo file changes
#       run: |
#         echo Changed files: ${{ steps.get_file_changes.outputs.files }}
