name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})"


# jobs:
#   build:
#     name: Build the Docker image
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
      
#     - name: Get file changes
#       id: get_file_changes
#       uses: dorner/file-changes-action@v1.2.0
#       with:
#         githubToken: ${{ secrets.GITHUB_TOKEN }}
#         plaintext: true

#     - name: Echo file changes
#       run: |
#         echo Changed files: ${{ steps.get_file_changes.outputs.files }}
