name: Docker Image CI

on:
  push:
#     branches: [ main ]
    tags: [ 'ci-*' ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changed files
      run: |
        changed_file_list=()
        for i in $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }});
        do
          changed_file_list += i
        done

        echo "::set-output name=CHANGED_FILES::${arr[@]}"
      id: changed_files

    - run: echo "the changed files are ${{steps.changed_files.outputs.CHANGED_FILES}}"

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
  
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1 
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ${{steps.changed_files.outputs.CHANGED_FILES}}
    #     push: true
    #     tags: |
    #       ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab-base:${{ steps.vars.outputs.tag }}
